name: vLLM image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build_vllm.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['24.12', '25.02']
    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Build and push image
        run: |
          docker pull nvcr.io/nvidia/tritonserver:${{matrix.version}}-vllm-python-py3
          docker tag nvcr.io/nvidia/tritonserver:${{matrix.version}}-vllm-python-py3 ${{vars.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.version}}-vllm
          docker push ${{vars.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.version}}-vllm